version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8005:80
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tom
      MYSQL_USER: tom
      MYSQL_PASSWORD: a

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8084:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
